name: Purge Cache

on: [push, workflow_dispatch]

jobs:
  speed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install requests
      - run: python ./.github/scripts/purge_cache.py
